/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as PaintingsRouteImport } from './routes/paintings'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaintingIdRouteImport } from './routes/painting.$id'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintingsRoute = PaintingsRouteImport.update({
  id: '/paintings',
  path: '/paintings',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintingIdRoute = PaintingIdRouteImport.update({
  id: '/painting/$id',
  path: '/painting/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/paintings': typeof PaintingsRoute
  '/sales': typeof SalesRoute
  '/statistics': typeof StatisticsRoute
  '/painting/$id': typeof PaintingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/paintings': typeof PaintingsRoute
  '/sales': typeof SalesRoute
  '/statistics': typeof StatisticsRoute
  '/painting/$id': typeof PaintingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/paintings': typeof PaintingsRoute
  '/sales': typeof SalesRoute
  '/statistics': typeof StatisticsRoute
  '/painting/$id': typeof PaintingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/paintings'
    | '/sales'
    | '/statistics'
    | '/painting/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/paintings' | '/sales' | '/statistics' | '/painting/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/paintings'
    | '/sales'
    | '/statistics'
    | '/painting/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PaintingsRoute: typeof PaintingsRoute
  SalesRoute: typeof SalesRoute
  StatisticsRoute: typeof StatisticsRoute
  PaintingIdRoute: typeof PaintingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paintings': {
      id: '/paintings'
      path: '/paintings'
      fullPath: '/paintings'
      preLoaderRoute: typeof PaintingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painting/$id': {
      id: '/painting/$id'
      path: '/painting/$id'
      fullPath: '/painting/$id'
      preLoaderRoute: typeof PaintingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PaintingsRoute: PaintingsRoute,
  SalesRoute: SalesRoute,
  StatisticsRoute: StatisticsRoute,
  PaintingIdRoute: PaintingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
